In [ ]:
!python --version

Python 3.9.1


<img src="Data/UP Data Science Society Logo 2.png" width=700>

# [2.1] Numpy Fundamentals and Manipulation
**Prepared by:**

- Dexter To

**Topics to cover:**
- Installing NumPy
- What is an array
- Python list vs NumPy array vs Tuple
- NumPy Operators
- NumPy Vectorization
- Manupulating `ndarray` (NumPy packages, Indexing, Assigning Values)


**Weekly Objectives:**

- Construct a ndarray NumPy
- Know the limits and advantages of NumPy compared to other built in packages
- Know the basic NumPy operations
- Perform basic NumPy Transformations

**References:**
- [Python documentation](https://docs.python.org/3/)
- [Numpy Lists](https://docs.python.org/3/tutorial/introduction.html#lists)
- [The N-dimensional array (ndarray)](https://numpy.org/doc/stable/reference/arrays.ndarray.html)
- [Tuples](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)
- [Numpy Data Types](https://numpy.org/doc/stable/user/basics.types.html)
- [Numpy Vectorization](https://towardsdatascience.com/how-to-speedup-data-processing-with-numpy-vectorization-12acac71cfca)
- [Numpy Array Manipulation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)
- [(Ivezic, Connolly, Vanderplas, Gray) Statistics, Data Mining, and Machine Learning in Astronomy](https://press.princeton.edu/books/hardcover/9780691198309/statistics-data-mining-and-machine-learning-in-astronomy)
- [365datascience; Numpy](https://365datascience.com/courses/data-preprocessing-numpy/)

**Note:** Some of the markdowns have been composed with the help of large language models, such as ChatGPT.

# I. Installing `NumPy`

NumPy (Numerical Python) is an open source Python library that's used in almost every field of science and engineering. It's the universal standard for working with numerical data in Python, and it's at the core of the scientific Python and PyData ecosystems.

To install NumPy, we strongly recommend using a scientific Python distribution. If you're looking for the full instructions for installing NumPy on your operating system, see [Installing NumPy](https://numpy.org/install/)

If you're running this in a Jupyter Notebook then you can install NumPy by using

If you are running it in Anaconda, use

To check the version you can do any of the any of the following:

In [ ]:
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
!pip show numpy

Name: numpy
Version: 1.22.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\lanz\anaconda3\envs\astro_env\lib\site-packages
Requires: 
Required-by: ale-py, APLpy, arviz, asdf, astroML, astroNN, astropy, astropy-healpix, astroquery, atari-py, autograd, blis, bokeh, Bottleneck, camelot-py, casa-formats-io, cftime, contourpy, dicom2nifti, emcee, folium, gym, h5py, hdbscan, holoviews, imageio, imgaug, isochrones, jplephem, Keras-Preprocessing, lightkurve, lmfit, mapclassify, matplotlib, moviepy, mujoco, mujoco-py, mw-plot, netCDF4, nibabel, numba, numexpr, oktopus, openai-whisper, opencv-python, opt-einsum, pandas, patsy, pyarrow, PyAstronomy, pyerfa, pymc3, pyregion, pystan, python-louvain, pytorch-lightning, PyWavelets, qutip, radio-beam, reproject, scikit-image, scikit-learn, scipy, seaborn, spacy, spectral-cube, statsmodels, tables, tabula-py, ten

If you're running this in the Anaconda platform, you can also use

In [ ]:
!conda list numpy

# packages in environment at C:\Users\Lanz\anaconda3\envs\astro_env:
#
# Name                    Version                   Build  Channel
numpy                     1.22.4                   pypi_0    pypi
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge


# II. `NumPy` basics

## A. What is an [`.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html)?

An array is a grid of values that contains the same data type, referred to as the array [`dtype`](https://numpy.org/doc/stable/reference/arrays.dtypes.html). It has a grid of elements that can be indexed in various ways.

Usually it is a fixed-size container of items of the same type and size. You might occasionally hear an array referred to as a `ndarray`, which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions.

To create a simple 1D array, use the `array()` module.

In [ ]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


Compared to Python's native `type()` that gives the data type of the variable itself,

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


`.dtype` gives the datatype of the elements within the array.

In [ ]:
print(a.dtype)

int32


Let's create `b`, another 1D array of strings.

In [ ]:
b = np.array(["1","2","3", ". .. ."])
print(b)

['1' '2' '3' '. .. .']


Checking the datatype, string elements default to a dtype of `<Un`, with n being the number of characters of the string with the highest number of characters, which in this case, `". .. ."` , which has 6 elements.

In [ ]:
print(b.dtype)

<U6


For arrays with n-dimensions.

- use `np.array([[],[],[]])` to construct a 3-dimension array
- use `np.array([[[],[],[]],[[],[],[]]])` to construct a 4-dimension array, etc

**Take note that the entire array is enclosed in a square bracket aside from the parenthesis**

In [ ]:
c = np.array([["1","2","3", "etc"],
              ["d","e","f", "etc"],
              ["h", "i", "j", "etc"]])
print(c)

[['1' '2' '3' 'etc']
 ['d' 'e' 'f' 'etc']
 ['h' 'i' 'j' 'etc']]


In [ ]:
print(c.dtype)

<U3


You can use the [`.shape`](https://numpy.org/doc/stable/reference/generated/numpy.shape.html) method to check the dimensions of your `ndarray`

In [ ]:
d = np.array([[["1","2","3", ". .. ."],
               ["d","e","f", "etc"],
               [ "h", "i", "j", "etc"]],

              [["1","2","3", ". .. ."],
               ["d","e","f", "etc"],
               ["h", "i", "j", "etc"]]])
print(d)

[[['1' '2' '3' '. .. .']
  ['d' 'e' 'f' 'etc']
  ['h' 'i' 'j' 'etc']]

 [['1' '2' '3' '. .. .']
  ['d' 'e' 'f' 'etc']
  ['h' 'i' 'j' 'etc']]]


By number of elements, `d` has an `axis(0)` of 2, `axis(1)` of 3, an `axis(2)` of 4.

[Axes](https://numpy.org/doc/stable/glossary.html#term-axis) are numbered left to right; axis 0 is the first element in the shape tuple.

In a two-dimensional vector, the elements of axis 0 are rows and the elements of axis 1 are columns.

In higher dimensions, the picture changes. `NumPy` prints higher-dimensional vectors as replications of row-by-column building blocks.

In [ ]:
d.shape

(2, 3, 4)

So remember, `(axis=0, axis=1, axis=2) -> (2, 3, 4)`

## B. Python list vs `NumPy` array vs Tuple
`list`, `ndarray`, and `tuple` are different ways used to store collections of elements. This is the overview of each type and their differences:

### 1. `list`
   - A list is a mutable, ordered collection of elements enclosed in square brackets (`[]`).
   - Lists can contain elements of different data types, such as integers, strings, or even other lists.
   - Elements within a list can be modified, added, or removed using various built-in methods like `append()`, `insert()`, `pop()`, and more.
   - Lists support indexing and slicing to access individual elements or sublists.

In [ ]:
my_list = [1, 2, 3, 'a', 'b', 'c']
for item in my_list:
    print(f"item: {item}, dtype: {type(item)}")

item: 1, dtype: <class 'int'>
item: 2, dtype: <class 'int'>
item: 3, dtype: <class 'int'>
item: a, dtype: <class 'str'>
item: b, dtype: <class 'str'>
item: c, dtype: <class 'str'>


### 2. `numpy.ndarray`
   - NumPy is a Python library for numerical computations, and `ndarray` is its core data structure.
   - An ndarray is a mutable, homogeneous, and multidimensional array.
   - It provides efficient storage and operations on large arrays of homogeneous data.
   - Elements within an ndarray must be of the same data type.
   - NumPy arrays have a fixed size and shape, defined upon creation.
   - ndarray offers a wide range of mathematical operations and functions for array manipulation.

In [ ]:
my_array = np.array([1, 2, 3, 4])
print(my_array.dtype)

int32


### 3. `tuple`
   - A tuple is an immutable, ordered collection of elements enclosed in parentheses (`()`), although the parentheses are often optional.
   - Tuples can contain elements of different data types, similar to lists.
   - Once created, the elements within a tuple cannot be modified.
   - Tuples are commonly used for representing a group of related values, such as coordinates or database records.
   - Tuple operations include indexing, slicing, and unpacking.

In [ ]:
my_tuple = (1, 2, 3, 'a', 'b', 'c')
for tuple in my_tuple:
    print(f"item: {tuple}, dtype: {type(tuple)}")

item: 1, dtype: <class 'int'>
item: 2, dtype: <class 'int'>
item: 3, dtype: <class 'int'>
item: a, dtype: <class 'str'>
item: b, dtype: <class 'str'>
item: c, dtype: <class 'str'>


Lists, arrays and tuples are alternatives to store data and each have different uses. All are ordered collection of items
To summarize:

| Type    | Mutability  | Homogeneity | Dimensions | Mutable Elements | Indexing | Common Use Cases                                 |
|---------|-------------|-------------|------------|------------------|----------|-------------------------------------------------|
| List    | Mutable     | No          | 1 (sequence) | Yes             | Yes      | Storing heterogeneous elements, dynamic changes |
| ndarray | Mutable     | Yes         | N (multidimensional) | No            | Yes      | Numerical computations, large homogeneous arrays |
| Tuple   | Immutable   | No          | 1 (sequence) | No               | Yes      | Storing related values, function return values   |

The "Homogeneity" column refers to whether the elements within the data structure must be of the same data type.

The "Dimensions" column refers to the number of dimensions or axes a data structure can have.


## C. `NumPy` **Element Wise-Operations**

`NumPy` operations allow us to manipulate arrays and perform various mathematical and logical operations efficiently. These operators enable us to perform element-wise operations, apply mathematical functions, compare arrays, and perform logical and bitwise operations.

Arithmetic operators in NumPy, such as addition, subtraction, multiplication, division, exponentiation, and floor division, enable us to perform mathematical computations on arrays effortlessly. These operators can work with arrays of different shapes and sizes, as well as scalar values.


Numpy can perform basic array arithmetic like addition, subtraction, multiplication and division of **element wise-operations** between similar shape arrays and with a scalar.

- Addition elements of two arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)

[5 7 9]


- Addition of scalar to an array

In [ ]:
arr1 = np.array([1, 2, 3])
scalar = 5

print(arr1 + scalar)

[6 7 8]


- Multiplication of two arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 * arr2)

[ 4 10 18]


- Comparison of two arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])

print(arr1 == arr2)

[False  True False]


- [`logical_and`](https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html) of two arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])

print(np.logical_and(arr1,arr2))

[ True  True  True]


### 1. Arithmetic Operators

| Category                  | Operator                                                                                              |
|---------------------------|-------------------------------------------------------------------------------------------------------|
| **Arithmetic Operators**  |                                                                                                       |
| Addition                  | +                                                                                                     |
| Subtraction               | -                                                                                                     |
| Division                  | /                                                                                                     |
| Floor Division            | //                                                                                                    |
| Exponentiation            | **                                                                                                    |

### 2. Comparison Operators

| Category                  | Operator                                                                                              |
|---------------------------|-------------------------------------------------------------------------------------------------------|
| Equal to                  | ==                                                                                                    |
| Not equal to              | !=                                                                                                    |
| Greater than              | >                                                                                                     |
| Less than                 | <                                                                                                     |
| Greater than or equal to  | >=                                                                                                    |
| Less than or equal to     | <=                                                                                                    |

### 3. Logical Operators

| Category                  | Operator                                                                                              |
|---------------------------|-------------------------------------------------------------------------------------------------------|
| Logical AND               | [`np.logical_and()`](https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html)         |
| Logical OR                | [`np.logical_or()`](https://numpy.org/doc/stable/reference/generated/numpy.logical_or.html)           |
| Logical NOT               | [`np.logical_not()`](https://numpy.org/doc/stable/reference/generated/numpy.logical_not.html)         |

### 4. Bitwise Operators

| Category                  | Operator                                                                                              |
|---------------------------|-------------------------------------------------------------------------------------------------------|
| Bitwise AND               | &                                                                                                     |
| Bitwise OR                | \|                                                                                                    |
| Bitwise XOR               | ^                                                                                                     |
| Bitwise NOT               | ~                                                                                                     |

### 5. Mathematical Functions

| Category                  | Operator                                                                                              |
|---------------------------|-------------------------------------------------------------------------------------------------------|
| Trigonometric functions   | [`np.sin()`](https://numpy.org/doc/stable/reference/generated/numpy.sin.html)                         |
|                           | [`np.cos()`](https://numpy.org/doc/stable/reference/generated/numpy.cos.html)                         |
|                           | etc.                                                                                                  |           
| Exponential functions     | [`np.exp()`](https://numpy.org/doc/stable/reference/generated/numpy.exp.html)                         |
|                           | [`np.log()`](https://numpy.org/doc/stable/reference/generated/numpy.log.html)                         |
|                           | etc.                                                                                                  |
| Square root               | [`np.sqrt()`](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)                       |
| Absolute value            | [`np.abs()`](https://numpy.org/doc/stable/reference/generated/numpy.abs.html)                         |
| Rounding functions        | [`np.round()`](https://numpy.org/doc/stable/reference/generated/numpy.round.html)                     |
|                           | [`np.floor()`](https://numpy.org/doc/stable/reference/generated/numpy.floor.html)                     |
|                           | [`np.ceil()`](https://numpy.org/doc/stable/reference/generated/numpy.ceil.html)                      |


## D. `NumPy` Vectorization
In NumPy, vectorization refers to the ability to perform operations on entire arrays or large portions of arrays at once, without the need for explicit loops. It leverages highly optimized C or Fortran code under the hood to process the arrays efficiently.

This approach provides several benefits, including concise and readable code, improved performance, and better utilization of computational resources.

When using vectorized operations in NumPy, mathematical operations are applied element-wise to arrays, eliminating the need for explicit loops. First, we define an arbitrary array `arr`, with 10000 elements:

In [ ]:
arr = np.array(np.arange(10_000))

To illustrate the difference between normal array manipulation and the built-in vectorized approach, let's consider an example where we want to calculate the square of each element in an array. By using the [`%%timeit`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit) cell magic:

In [ ]:
%%timeit

result = arr.copy()
for i in range(len(arr)):
    result[i] = arr[i] ** 2

result = np.array(result)

3.15 ms ± 46.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In the code above, we manually iterate over each element of the array `arr` using a `for` loop and calculate the square of each element.

This approach requires explicit iteration and assignment for each element, which can be slower and less concise for larger arrays.

In the vectorized approach, we simply apply the exponentiation operation ** directly to the array `arr`, and NumPy automatically performs the element-wise computation.

In [ ]:
%%timeit

arr = np.array(np.arange(10000))
result = arr ** 2

13.3 µs ± 61.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


This approach is more concise and efficient as it leverages the underlying optimized code for element-wise operations.

## E. NumPy Array Manipulation
Aside from the basic numerical operators, aray manipulation in NumPy involves a wide range of operations, including reshaping arrays, transposing dimensions, changing array structure, resizing and repeating elements, changing array order, slicing and indexing, sorting and searching, and more.

Numpy array can also be manipulated in differetn ways. For example, NumPy array manipulation can transform the figure below.

<img src=https://i.redd.it/j3pi4oi456521.png width=400>

### 1. Adding two Arrays: [`np.sum()`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)
This example shows the most common array manipulation using `np.sum()`.

When you use `np.sum()`, NumPy adds up all the elements of the array and returns the total sum. It treats the array as a one-dimensional sequence and sums all the values. Let's define another arbitrary `array`, but it's a 2D array instead.

In [ ]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

You can also specify an axis parameter to compute the sum along a particular axis. If you have a multi-dimensional array, the axis parameter allows you to specify the dimension along which the sum will be calculated.

- Sum all elements of the array

In [ ]:
print("Total Sum:", np.sum(array))

Total Sum: 21


- Sum along the columns `(axis=0)`

In [ ]:
print("Column Sums:", np.sum(array, axis=0))

Column Sums: [5 7 9]


- Sum along the rows `(axis=1)`

In [ ]:
print("Row Sums:", np.sum(array, axis=1))

Row Sums: [ 6 15]


### 2. Operating two Arrays: [`np.matmul()`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)

This example shows the most common array manipulation using `np.matmul()`.

Let's define a 3x2 array `A`,

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

 and a 2x3 array `B`:

In [ ]:
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

Matrix multiplication involves taking the dot product of corresponding rows and columns of the matrices and summing up the results to produce a new matrix. Hence, operating a $m \times n$ matrix with $n \times l$ will produce a matrix of shape $m \times l$.

In [ ]:
print("Matmul result:\n", np.matmul(A, B))

Matmul result:
 [[ 58  64]
 [139 154]]


### 3. Reshaping Arrays: [`np.reshape()`]((https://numpy.org/doc/stable/reference/generated/numpy.reshape.html))

The example demonstrates reshaping a 1D array into a 2D array using `np.reshape()`.

It takes the original array and specifies the desired shape as arguments.

Let's define another arbitrary array `arr` with 10 elements:

In [ ]:
arr = np.arange(10)

- Create `reshaped_arr` by reshaping `arr` to a 2D array with 2 rows and 5 columns.

In [ ]:
reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr.shape)

(2, 5)


The resulting reshaped array has the specified shape while maintaining the original elements.

In [ ]:
print("Original array:\n",arr)
print("Reshaped array:\n",reshaped_arr)

Original array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


### 4. Transposing Arrays: [`np.transpose()`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

This example showcases transposing an array using `np.transpose()`.

It rearranges the dimensions of the array, effectively swapping the rows and columns. The resulting transposed array has the dimensions reversed compared to the original array.

- Create a 2D array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

- Transpose the array

In [ ]:
transposed_arr = arr.transpose()

- Print to create the comparison of the two arrays

In [ ]:
print("Original array:\n", arr)
print("Transposed array:\n",transposed_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


### 5. Joining Arrays: [`np.concatenate()`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

The example focuses on joining multiple arrays along an existing axis using `np.concatenate()` .

It takes the arrays to be joined as arguments and concatenates them along the specified axis. The resulting array contains all the elements from the input arrays.

Note that the two arrays should be of the same dimension.

- Create arrays `arr1` and `arr2`

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

- Concatenate the arrays along the first axis

In [ ]:
joined_arr1 = np.concatenate((arr1, arr2))
print(joined_arr1)

[1 2 3 4 5 6]


- Create arrays `arr3` and `arr4`

In [ ]:
arr3 = np.array([[1, 2, 3],[4, 5, 6]])
arr4 = np.array([[7, 8, 9],[10, 11, 12]])

- Concatenate the arrays along the first axis

In [ ]:
joined_arr2 = np.concatenate((arr3, arr4))
print(joined_arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


- Concatenate the arrays along the second axis

In [ ]:
joined_arr2 = np.concatenate((arr3, arr4), axis=1)
print(joined_arr2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


- Create arrays `arr5` and `arr6`

In [ ]:
arr5 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]]])
arr6 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]]])

- Concatenate the arrays along the first axis
- Print the shape before and after the concatenation and results

In [ ]:
joined_arr3 = np.concatenate((arr5, arr6))
print("Shape of arr5 and arr6 before:",arr5.shape)
print("Shape of combined arr5 and arr6:",joined_arr3.shape)
print(f'joined_arr3: \n{joined_arr3}')

Shape of arr5 and arr6 before: (2, 3, 3)
Shape of combined arr5 and arr6: (4, 3, 3)
joined_arr3: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


### 6. Repeating Arrays:[`np.repeat()`](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html)

This example demonstrates repeating elements of an array along a specified axis using `np.repeat()`.

It takes the array and the repetition count as arguments. The resulting array contains the original elements repeated as specified.

- Repeat each element three times

In [ ]:
arr = np.array([1, 2, 3])
repeated_arr = np.repeat(arr, 3)
print(repeated_arr)

[1 1 1 2 2 2 3 3 3]


Note that `np.repeat()` can also be oriented towards any axis of choice.

In [ ]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print("arr: \n",arr,"\n with shape:",arr.shape)

arr: 
 [[1 2 3]
 [4 5 6]] 
 with shape: (2, 3)


- Repeat each element three times

In [ ]:
repeated_arr = np.repeat(arr, 3)
print("repeated_arr: \n",repeated_arr,"\n with shape:",repeated_arr.shape)

repeated_arr: 
 [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6] 
 with shape: (18,)


- Repeat each element three times along y axis

In [ ]:
repeated_arry = np.repeat(arr, 3, axis=0)
print("repeated_arry: \n",repeated_arry,"\n with shape:",repeated_arry.shape)

repeated_arry: 
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]] 
 with shape: (6, 3)


- Repeat each element three times along x axis

In [ ]:
repeated_arrx = np.repeat(arr, 3, axis=1)
print("repeated_arrx: \n",repeated_arrx,"\n with shape:",repeated_arrx.shape)

repeated_arrx: 
 [[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]] 
 with shape: (2, 9)


### 7. Sorting and Searching: [`np.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

This example focuses on sorting an array in ascending order using  `np.sort()`.

It rearranges the elements of the array in place, resulting in a sorted array.
- Sort the array in ascending order

In [ ]:
sorted_arr = np.sort(arr)
print(sorted_arr)

[[1 2 3]
 [4 5 6]]


- Sort the array in alphabetical order

In [ ]:
arr = np.array(['cat','dog','mouse','horse'])
sorted_arr = np.sort(arr)
print(sorted_arr)

['cat' 'dog' 'horse' 'mouse']


- Sort each array in ascending order

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
sorted_arr = np.sort(arr)
print(sorted_arr)

[[2 3 4]
 [0 1 5]]


### 8. [Slicing and Indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html)

Just like lists:
- Strings can be indexed (subscripted), with the first character having index `0`. There is no separate character type
- a character is simply a string of size one.
- **Counting in Python starts with 0**

Supposed we have an array:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

- Accessing a single element

In [ ]:
print(arr[0])

1


- Accessing the last element

In [ ]:
print(arr[-1])

5


Notice that we access the `ndarray` the same as how we accesss `lists`.
Just like `lists` NumPy can be sliced via the following:
- **slicing `[start:end:interval]`**
- Like strings (and all other built-in sequence types), lists can be indexed and sliced.
- All slice operations return a new list containing the requested elements.

- Accessing a range of elements

In [ ]:
print(arr[1:4])

[2 3 4]


- Slicing with a step size of 2

In [ ]:
print(arr[::2])

[1 3 5]


- Slicing with a step size of -1 (reversing order)

In [ ]:
print(arr[::-1])

[5 4 3 2 1]


For 2D arrays, use comma to slice the other axes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

- Accessing a specific element

In [ ]:
print(arr[1, 2])

6


- Accessing an entire row

In [ ]:
print(arr[1])

[4 5 6]


- Accessing a column

In [ ]:
print(arr[:, 1])

[2 5 8]


- Slicing a subarray

In [ ]:
print(arr[:2, 1:])

[[2 3]
 [5 6]]


The same goes for slicing a 3 and 4 Dimensional arrays.

A 3 Dimensional array slicing and indexing example:

In [ ]:
arr = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],

                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

- Accessing a specific element

In [ ]:
print(arr[0, 1, 2])

6


- Accessing an entire 2D array (slice)

In [ ]:
print(arr[1])

[[10 11 12]
 [13 14 15]
 [16 17 18]]


- Accessing a specific column across all 2D arrays

In [ ]:
print(arr[:, :, 1])

[[ 2  5  8]
 [11 14 17]]


A 4 Dimensional array slicing and indexing example:

In [ ]:
arr = np.array([[[[1, 2],
                  [3, 4]],

                 [[5, 6],
                  [7, 8]]],

                [[[9, 10],
                  [11, 12]],

                 [[13, 14],
                  [15, 16]]]])

-  Accessing a specific element

In [ ]:
print(arr[0, 1, 0, 1])

6


-  Accessing an entire 3D array (slice)

In [ ]:
print(arr[1])

[[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


- Accessing a specific row across all 3D arrays

In [ ]:
print(arr[:, :, 1, :])

[[[ 3  4]
  [ 7  8]]

 [[11 12]
  [15 16]]]


Since NumPy arrays are mutable, its indexes can be changed, revised and appended.

Consider the following 2D array example:

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

We can assign new values in the indexes via the square brackets `[]` with specified axis needed to change. (Refer to the slicing guide above)

In this example, we assigned a single element to a single entry
- Assigning a new value to a specific element

In [ ]:
arr[1, 1] = 10
print(arr)

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


We can also assign a single element to a sliced array
- Assigning a new value to a specific axis

In [ ]:
arr[1] = 10

print(arr)

[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]]


Or to other axis
- Assigning a new value to a specific axis

In [ ]:
arr[:,1] = 10

print(arr)

[[ 1 10  3]
 [10 10 10]
 [ 7 10  9]]


We can also assign other `ndarray` values as well
- Assigning new values to a range of elements

In [ ]:
arr[0, 1:3] = [20, 30]

print(arr)

[[ 1 20 30]
 [10 10 10]
 [ 7 10  9]]


**End of tutorial.**

---

# III. Sample exercises

Try to solve exercises these exercises if you like.

## Exercise 1

You are given a list of names and corresponding scores of students in a class. Your task is to write a program that sorts the scores in non-decreasing order and returns a new list of names corresponding to the sorted scores.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Write a function called `sort_scores(names, scores)` that takes two lists as input: `names` (a list of strings representing the names of the students) and `scores` (a list of integers representing the scores of the students). The function should return a new list of names containing the names corresponding to the scores sorted in non-decreasing order.

## Exercise 2

A permutation matrix is a special type of square matrix that represents a permutation of the rows or columns of an identity matrix. Every row and columns contains precisely a single $1$ with $0$s everywhere else, and every permutation corresponds to a unique permutation matrix.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; For a $2 \times 2$ matrix, the possible permutation matrix are:

\begin{equation*}
\begin{bmatrix}1\ & 0\\ 0\ & 1\end{bmatrix}\qquad
\begin{bmatrix}0\ & 1\\ 1\ & 0\end{bmatrix}
\end{equation*}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; For a $3 \times 3$ matrix, the possible permutation matrices are:


\begin{equation*}
\begin{bmatrix} 1\ & 0\ & 0 \\ 0\ & 1\ & 0 \\ 0\ & 0\ & 1 \end{bmatrix} \qquad
\begin{bmatrix} 1\ & 0\ & 0 \\ 0\ & 0\ & 1 \\ 0\ & 1\ & 0 \end{bmatrix} \qquad
\begin{bmatrix} 0\ & 1\ & 0 \\ 1\ & 0\ & 0 \\ 0\ & 0\ & 1 \end{bmatrix} \qquad
\begin{bmatrix} 0\ & 0\ & 1 \\ 1\ & 0\ & 0 \\ 0\ & 1\ & 0 \end{bmatrix} \qquad
\begin{bmatrix} 0\ & 1\ & 0 \\ 0\ & 0\ & 1 \\ 1\ & 0\ & 0 \end{bmatrix} \qquad
\begin{bmatrix} 0\ & 0\ & 1 \\ 0\ & 1\ & 0 \\ 1\ & 0\ & 0 \end{bmatrix}
\end{equation*}


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The fun property of multiplying a matrix to a permutation matrix vice versa is that they jumble the arrangement of the rows and/or columns of the matrix.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Suppose we have a $4 \times 4$ matrix with elements:

\begin{bmatrix}
1 & 1 & 1 & 1 \\
3 & 3 & 3 & 3 \\
2 & 2 & 2 & 2 \\
4 & 4 & 4 & 4 \\
\end{bmatrix}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **What is the corresponding matrix needed to align the matrix to:**

\begin{bmatrix}
1 & 1 & 1 & 1 \\
2 & 2 & 2 & 2 \\
3 & 3 & 3 & 3 \\
4 & 4 & 4 & 4 \\
\end{bmatrix}

